import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, Search } from "lucide-react";
import productService from "@/features/products/services/productService";
import type { Product } from "@/features/products/types/product.types";

export function InventoryPage() {
  const [products, setProducts] = useState<Product[]>([]); const [query, setQuery] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { void productService.getProducts({ status: "ALL", limit: 100 }).then((response) => setProducts(response.data.data.items)).catch(() => setError("Không thể tải tồn kho.")).finally(() => setLoading(false)); }, []);
  const rows = useMemo(() => products.flatMap((product) => (product.variants ?? []).map((variant) => ({ product, variant }))).filter(({ product, variant }) => !query || `${product.name} ${variant.sku}`.toLowerCase().includes(query.toLowerCase())), [products, query]);
  const lowStock = rows.filter(({ variant }) => variant.stockQuantity <= 5).length;
  return <div className="space-y-5"><div><h1 className="text-xl font-bold">Inventory</h1><p className="text-sm text-gray-500">Theo dõi tồn kho theo SKU và biến thể</p></div><div className="grid gap-3 sm:grid-cols-3"><div className="rounded-lg border bg-white p-4"><p className="text-xs text-gray-500">Tổng SKU</p><p className="mt-1 text-2xl font-bold">{rows.length}</p></div><div className="rounded-lg border bg-white p-4"><p className="text-xs text-gray-500">Sắp hết hàng</p><p className="mt-1 text-2xl font-bold text-amber-600">{lowStock}</p></div><div className="rounded-lg border bg-white p-4"><p className="text-xs text-gray-500">Sản phẩm</p><p className="mt-1 text-2xl font-bold">{products.length}</p></div></div>{error && <p className="rounded bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="relative"><Search className="absolute left-3 top-2.5 text-gray-400" size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Tìm sản phẩm hoặc SKU..." className="w-full rounded border py-2 pl-9 pr-3 text-sm" /></div><div className="overflow-x-auto rounded-lg border bg-white"><table className="w-full text-left text-sm"><thead className="border-b bg-gray-50 text-xs uppercase text-gray-500"><tr><th className="px-4 py-3">Sản phẩm</th><th className="px-4 py-3">SKU</th><th className="px-4 py-3">Thuộc tính</th><th className="px-4 py-3">Tồn kho</th><th className="px-4 py-3">Trạng thái</th></tr></thead><tbody className="divide-y">{loading ? <tr><td colSpan={5} className="py-10 text-center">Đang tải tồn kho...</td></tr> : rows.map(({ product, variant }) => <tr key={variant.id}><td className="px-4 py-3 font-medium">{product.name}</td><td className="px-4 py-3 font-mono text-xs">{variant.sku}</td><td className="px-4 py-3 text-gray-500">{Object.entries(variant.attributes ?? {}).map(([key, value]) => `${key}: ${String(value)}`).join(" · ") || "—"}</td><td className="px-4 py-3 font-semibold">{variant.stockQuantity}</td><td className="px-4 py-3">{variant.stockQuantity === 0 ? <span className="text-red-600">Hết hàng</span> : variant.stockQuantity <= 5 ? <span className="inline-flex items-center gap-1 text-amber-600"><AlertTriangle size={14} />Sắp hết</span> : <span className="text-emerald-600">Còn hàng</span>}</td></tr>)}{!loading && !rows.length && <tr><td colSpan={5} className="py-10 text-center text-gray-500">Không có SKU phù hợp.</td></tr>}</tbody></table></div></div>;
}
