import { useEffect, useMemo, useState } from "react";
import { Eye, Search, Trash2 } from "lucide-react";
import api from "@/lib/api";
import { DataTablePagination } from "@/components/DataTablePagination";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";

interface Review { id: string; rating: number; comment?: string | null; createdAt: string; user: { name: string; email?: string }; product?: { id: string; name: string }; }

export function ReviewsPage() {
  const [reviews, setReviews] = useState<Review[]>([]); const [query, setQuery] = useState(""); const [page, setPage] = useState(1); const [selected, setSelected] = useState<Review | null>(null); const [error, setError] = useState("");
  const load = async () => { try { const response = await api.get<{ data: Review[] }>("/reviews"); setReviews(response.data.data); setError(""); } catch { setError("Không thể tải đánh giá."); } };
  useEffect(() => { void load(); }, []);
  const filtered = useMemo(() => reviews.filter((review) => !query || `${review.user.name} ${review.product?.name ?? ""} ${review.comment ?? ""}`.toLowerCase().includes(query.toLowerCase())), [reviews, query]);
  const pages = Math.max(1, Math.ceil(filtered.length / 10)); const visible = filtered.slice((page - 1) * 10, page * 10);
  const remove = async (id: string) => { if (!window.confirm("Xóa đánh giá này?")) return; try { await api.delete(`/reviews/${id}`); await load(); } catch { setError("Không thể xóa đánh giá."); } };
  return <div className="space-y-4"><div><h1 className="text-xl font-bold">Reviews</h1><p className="text-sm text-gray-500">Kiểm duyệt đánh giá của khách hàng</p></div>{error && <p className="rounded bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="relative"><Search className="absolute left-3 top-2.5 text-gray-400" size={16} /><input value={query} onChange={(event) => { setQuery(event.target.value); setPage(1); }} placeholder="Tìm theo khách hàng, sản phẩm..." className="w-full rounded border py-2 pl-9 pr-3 text-sm" /></div><div className="overflow-hidden rounded-lg border"><Table><TableHeader><TableRow><TableHead>Khách hàng</TableHead><TableHead>Sản phẩm</TableHead><TableHead>Đánh giá</TableHead><TableHead>Ngày gửi</TableHead><TableHead className="text-right">Tùy chọn</TableHead></TableRow></TableHeader><TableBody>{visible.map((review) => <TableRow key={review.id}><TableCell className="font-medium">{review.user.name}</TableCell><TableCell>{review.product?.name ?? "—"}</TableCell><TableCell><span className="text-amber-500">{"★".repeat(review.rating)}{"☆".repeat(5 - review.rating)}</span></TableCell><TableCell>{new Date(review.createdAt).toLocaleDateString("vi-VN")}</TableCell><TableCell className="text-right"><button type="button" onClick={() => setSelected(review)} className="rounded p-2 hover:bg-gray-100" aria-label="Xem đánh giá"><Eye size={16} /></button><button type="button" onClick={() => void remove(review.id)} className="rounded p-2 text-red-600 hover:bg-red-50" aria-label="Xóa đánh giá"><Trash2 size={16} /></button></TableCell></TableRow>)}{!visible.length && <TableRow><TableCell colSpan={5} className="py-10 text-center text-sm text-gray-500">Chưa có đánh giá.</TableCell></TableRow>}</TableBody></Table><DataTablePagination currentPage={page} totalPages={pages} onPageChange={setPage} /></div>{selected && <div className="fixed inset-0 z-30 flex items-center justify-center bg-black/40 p-4"><div className="w-full max-w-lg rounded-lg bg-white p-5"><div className="flex items-center justify-between"><h2 className="font-semibold">Chi tiết đánh giá</h2><button type="button" onClick={() => setSelected(null)}>Đóng</button></div><p className="mt-4 text-amber-500">{"★".repeat(selected.rating)}{"☆".repeat(5 - selected.rating)}</p><p className="mt-3 text-sm text-gray-700">{selected.comment || "Không có nội dung."}</p></div></div>}</div>;
}
