import { Star } from "lucide-react";
import { Link } from "react-router-dom";
import { formatMoney } from "@/lib/formatters";
import type { Product } from "@/types/product";

interface ProductShowcaseProps { id?: string; title: string; products: Product[]; loading?: boolean }

export function ProductShowcase({ id, title, products, loading = false }: ProductShowcaseProps) {
  return <section id={id} className="py-16 sm:py-20"><h2 className="home-display text-center text-[32px] sm:text-5xl">{title}</h2>{loading ? <div className="mt-8 grid grid-cols-2 gap-4 sm:mt-12 lg:grid-cols-4 lg:gap-5">{Array.from({ length: 4 }, (_, index) => <div key={index} className="animate-pulse"><div className="aspect-square rounded-2xl bg-black/10" /><div className="mt-3 h-4 w-3/4 rounded bg-black/10" /><div className="mt-2 h-4 w-1/3 rounded bg-black/10" /></div>)}</div> : products.length ? <div className="mt-8 grid grid-cols-2 gap-4 sm:mt-12 lg:grid-cols-4 lg:gap-5">{products.slice(0, 4).map((product) => { const price = product.variants[0]?.price ?? product.basePrice; return <article key={product.id} className="group min-w-0"><Link to={`/products/${product.slug}`} className="block"><div className="aspect-square overflow-hidden rounded-2xl bg-[#f0eeed]">{product.thumbnail ? <img src={product.thumbnail} alt={product.name} loading="lazy" className="h-full w-full object-cover transition duration-500 group-hover:scale-105" /> : <div className="flex h-full items-center justify-center text-sm text-black/40">Chưa có ảnh</div>}</div><h3 className="mt-3 truncate text-sm font-bold sm:text-base">{product.name}</h3></Link><div className="mt-1.5 flex items-center gap-1 text-[#ffc633]" aria-label={`${product.rating ?? 4.5} trên 5 sao`}>{Array.from({ length: 5 }, (_, index) => <Star key={index} size={15} className={index < Math.round(product.rating ?? 4.5) ? "fill-current" : "fill-current opacity-30"} />)}<span className="ml-1 text-xs text-black/60">{(product.rating ?? 4.5).toFixed(1)}</span></div><p className="mt-1.5 text-lg font-bold sm:text-2xl">{formatMoney(price)}</p></article>; })}</div> : <p className="mt-10 text-center text-sm text-black/50">Chưa có sản phẩm để hiển thị.</p>}<div className="mt-8 text-center sm:mt-10"><Link to="/shop" className="inline-flex h-[52px] w-full items-center justify-center rounded-full border border-black/10 text-sm font-medium transition hover:bg-black hover:text-white sm:w-[218px]">Xem tất cả</Link></div></section>;
}
