import { Link } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import { ClipboardList, Heart, KeyRound, MapPin, ShoppingBag, UserRound } from "lucide-react";
import { accountApi } from "@/features/account/api/accountApi";
import { StatusBadge } from "@/features/account/components/StatusBadge";
import { formatDate, formatMoney } from "@/lib/formatters";
import { ErrorState } from "@/components/feedback/ErrorState";

const quickLinks = [{ to: "/account/profile", label: "Sửa thông tin cá nhân", icon: UserRound }, { to: "/account/addresses", label: "Sổ địa chỉ", icon: MapPin }, { to: "/account/profile/password", label: "Đổi mật khẩu", icon: KeyRound }, { to: "/account/orders", label: "Theo dõi đơn hàng", icon: ClipboardList }];

export function AccountPage() {
  const overview = useQuery({ queryKey: ["account-overview"], queryFn: accountApi.overview });
  if (overview.isLoading) return <div className="space-y-4"><div className="h-28 animate-pulse rounded-2xl bg-black/5" /><div className="grid gap-3 sm:grid-cols-3"><div className="h-28 animate-pulse rounded-2xl bg-black/5" /><div className="h-28 animate-pulse rounded-2xl bg-black/5" /><div className="h-28 animate-pulse rounded-2xl bg-black/5" /></div></div>;
  if (overview.isError || !overview.data) return <ErrorState message="Không thể tải tổng quan tài khoản." onRetry={() => void overview.refetch()} />;
  const { user, stats, recentOrders } = overview.data;
  const statCards = [{ label: "Tổng đơn hàng", value: stats.totalOrders, icon: ShoppingBag }, { label: "Đang xử lý", value: stats.pendingOrders, icon: ClipboardList }, { label: "Sản phẩm yêu thích", value: stats.wishlistCount, icon: Heart }];
  return <div><div className="rounded-2xl bg-black p-5 text-white sm:p-7"><div className="flex items-center gap-4"><div className="flex size-16 shrink-0 items-center justify-center overflow-hidden rounded-full bg-white/15 text-lg font-bold">{user.avatarUrl ? <img src={user.avatarUrl} alt="" className="h-full w-full object-cover" /> : user.name.slice(0, 1).toUpperCase()}</div><div><p className="text-sm text-white/60">Xin chào,</p><h1 className="text-2xl font-black">{user.name}</h1><p className="mt-1 text-sm text-white/65">{user.email}</p></div></div></div><div className="mt-4 grid gap-3 sm:grid-cols-3">{statCards.map(({ label, value, icon: Icon }) => <div key={label} className="rounded-2xl border border-black/10 bg-white p-5"><Icon size={20} className="text-black/45" /><p className="mt-4 text-3xl font-black">{value}</p><p className="mt-1 text-sm text-black/55">{label}</p></div>)}</div><div className="mt-8 grid gap-6 lg:grid-cols-[1fr_300px]"><section><div className="flex items-center justify-between"><h2 className="text-xl font-bold">Đơn hàng gần đây</h2><Link to="/account/orders" className="text-sm font-semibold underline">Xem tất cả</Link></div>{recentOrders.length ? <div className="mt-4 space-y-3">{recentOrders.map((order) => <Link to={`/account/orders/${order.id}`} key={order.id} className="flex items-center gap-3 rounded-2xl border border-black/10 bg-white p-4 transition hover:border-black"><span className="flex size-10 shrink-0 items-center justify-center rounded-full bg-black/5"><ShoppingBag size={18} /></span><span className="min-w-0 flex-1"><strong className="block truncate">Đơn #{order.id.slice(0, 8)}</strong><span className="mt-1 block text-xs text-black/50">{formatDate(order.createdAt)}</span></span><span className="flex shrink-0 flex-col items-end gap-2"><StatusBadge status={order.status} /><strong className="text-sm">{formatMoney(order.total)}</strong></span></Link>)}</div> : <p className="mt-4 rounded-2xl border border-dashed border-black/15 p-6 text-sm text-black/55">Bạn chưa có đơn hàng nào.</p>}</section><aside><h2 className="text-xl font-bold">Truy cập nhanh</h2><div className="mt-4 space-y-2">{quickLinks.map(({ to, label, icon: Icon }) => <Link key={to} to={to} className="flex min-h-12 items-center gap-3 rounded-xl border border-black/10 bg-white px-4 text-sm font-medium transition hover:border-black"><Icon size={18} className="text-black/55" />{label}</Link>)}</div></aside></div></div>;
}
